### ISSUE TITLE
Student agreement location

### ISSUE THREAD

**Issue by shiryz** [foundersandcoders/nazareth-programme#228]
atm we are linking to this [student agreement](https://github.com/foundersandcoders/nazareth-programme/blob/master/student-agreement.md) which says fac1 student agreement and will be replaced with [this](https://github.com/foundersandcoders/nazareth-programme/issues/213). the thing is nazareth-programme is a private repo, I suggest we move the student agreement to the master reference.

**Comment by rebeccaradding** [comment]
@shiryz it's now public, want to update the student agreement here in this repo now?

**Comment by shiryz** [comment]
yes I'll do that

**Comment by shiryz** [comment]
Closing the repo is public now
